app:
  appdescription: 'microservicio plazoleta'
  appversion: '1.0.0'

server:
  port: 8086

spring:
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java

  datasource:
    url: jdbc:mysql://localhost:3306/microservice_plazoleta
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    mongodb:
      host: localhost
      port: 27017
      database: microservice_plazoleta

  cloud:
    config:
      enabled: false


debug: true